[project]
name = "ccf2d"
version = "0.1.0"
description = "Tools for do the 2d mouse brain registration"
readme = "README.md"
authors = [
    { name = "Yu-Ting Wei", email = "ytsimon2004@gmail.com" },
]
requires-python = ">=3.12"
dependencies = [
    "argclz>=1.0.1",
    "neura-library[atlas]>=0.5.2",
    "numba>=0.60"
]

[project.optional-dependencies]

doc = [
    'sphinx',
    'pydata-sphinx-theme',
    'sphinx_copybutton'
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project.scripts]
ccf2d = "ccf2d.__main__:main"
